language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Z2+GuyIwZYgmbzOGCP7IiomRcfYPU/uRJH6K4hi5/Pjo1mzhLne6lwUg+0TD6p1xnybhdwLrfEceiS/bMhZXd//ehwxEo5Vimq/gvczzbtW8no5ZcP4nT4cY+2Xn49xfewfxEecX62EHt3LgYc8z1dkUdvK+5cNAoqpj/3zGyG6i2tOXZeZMMRqv6QagaAK0Q4kM1/mRrUmsOlN/wFS4YdtdrnCyhplPIYuGNefPznPfg8IiB1daTPIOdHTpb9ZIUjYDHozHkj0n/vjhIfcMqZE1HEyS5s8rDJCxTMAWxrimlnBHxseOXOCWjirp+s6LkabEAbkn80kJnfW4i/Y/VLg5BccgrFei+hSELTCOmmWKorYlmquLNfjFagy3FXgIzv73nsWCOmmNXGCTMxXLjG8OVwTcYcCiGlXodh2BSpk+dP2k6Jkwmpw7AuVslg/YtKohedXv9u72oMnNVBDgMCKfWxgk3CexI/jr44esQ0Fxd3gYSC/+3wTvpZctJ1h4r3ywwvjD0yXeVMvxvxn5nQHYIiSCPFQlSDCD0u0KfzPBsiYiTyKOriwXD9fHVMNexMjIqtBrLsIoa+AQ3ejEtaxo3C7HAqxG1QlwNjaLUrJgxajSpTwpOKV9QutgSWZKkj80cuRZ6NxEe3jiuohxLXPQuo+xjLOfY5UHWDx0YG8=
  app: whispering-temple-74903
  on:
    repo: deepbsd/node-restaurants-app-mongoose-ci
    branch: feature/with-tests
